package us.smartmc.backend.command;

import com.google.gson.Gson;
import us.smartmc.backend.connection.ConnectionHandler;
import us.smartmc.backend.handler.PlayerContextsHandler;
import us.smartmc.backend.instance.BackendCommandExecutor;
import us.smartmc.backend.instance.handler.MapHandler;
import us.smartmc.backend.instance.player.PlayerCache;

import java.util.UUID;

public class GetPlayerCacheCmd extends BackendCommandExecutor {

    public GetPlayerCacheCmd() {
        super("getPlayerCache");
    }

    @Override
    public void onCommand(ConnectionHandler connection, String label, String[] args) {
        UUID playerId = UUID.fromString(args[0]);
        PlayerCache cache = MapHandler.getHandler(PlayerContextsHandler.class)
                .getCache(playerId);
        connection.sendCommand("setPlayerCache " + "{\n" +
                "  \"_id\": \"5f257be9-0c62-4b17-ab8a-4ad53f9acb44\",\n" +
                "  \"lang\": \"CONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRECONTEONETEOUHONGCON  CONEOTNO EIRJO IJREGOIJEQ OGPIJQPOEI RJGOPQIEJRGOJQOEI JRGOJQE ORGJQEORI JGOQPIEJGOIRE\"\n" +
                "}");
    }
}
