main: us.smartmc.core.SmartCore
name: SmartCore23
version: 1.0-SNAPSHOT
authors:
  - ImSergioh

commands:
  admin:
  setspawn:
  spawn:
  language:
    aliases: [lang, lenguaje]
  reloadLanguageConfig:
  gamemode:
    aliases: [gm]
    description: Change your gamemode
  region:
  executeAtBungeeCommand:
  friend:
    aliases: [friends]
  coins:
    aliases: [balance, eco, bal]